### ISSUE TITLE
StandardHighBandwidthNetworkMediator check failure

### ISSUE THREAD

**Issue by yschimke** [google/horologist#1092]
```
Fatal Exception: java.lang.IllegalStateException: Check failed.
       at com.google.android.horologist.networks.highbandwidth.StandardHighBandwidthNetworkMediator$actuallyRelease$1.invoke(StandardHighBandwidthNetworkMediator.java:63)
       at com.google.android.horologist.networks.highbandwidth.StandardHighBandwidthNetworkMediator$actuallyRelease$1.invoke(StandardHighBandwidthNetworkMediator.java:2)
       at com.google.android.horologist.networks.highbandwidth.StandardHighBandwidthNetworkMediator$Requests.update(StandardHighBandwidthNetworkMediator.java:21)
       at com.google.android.horologist.networks.highbandwidth.StandardHighBandwidthNetworkMediator.actuallyRelease(StandardHighBandwidthNetworkMediator.java:9)
       at com.google.android.horologist.networks.highbandwidth.StandardHighBandwidthNetworkMediator.processCancel(StandardHighBandwidthNetworkMediator.java:85)
       at com.google.android.horologist.networks.highbandwidth.StandardHighBandwidthNetworkMediator.access$processCancel(StandardHighBandwidthNetworkMediator.java)
       at com.google.android.horologist.networks.highbandwidth.StandardHighBandwidthNetworkMediator$processCancel$1.invokeSuspend(StandardHighBandwidthNetworkMediator.java:12)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:11)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:88)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:14)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:28)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java)
```

**Comment by yschimke** [comment]
Hopefully fixed, will reopen if reoccurs.
