### ISSUE TITLE
Divide by zero issue

### ISSUE THREAD

**Issue by garanj** [google/horologist#1108]
Got the following crash today:

```
java.lang.ArithmeticException: divide by zero

java.lang.ArithmeticException
at com.google.android.horologist.compose.rotaryinput.ScalingLazyColumnRotaryScrollAdapter.averageItemSize
at com.google.android.horologist.compose.rotaryinput.DefaultSnapBehavior.snapThreshold
at com.google.android.horologist.compose.rotaryinput.RotaryScrollSnapHandler.handleScrollEvent
at com.google.android.horologist.compose.rotaryinput.RotaryKt$rotaryHandler$<anonymous>$<anonymous>$<anonymous>$<anonymous>.invokeSuspend
  at com.google.android.horologist.compose.rotaryinput.ScalingLazyColumnRotaryScrollAdapter.averageItemSize(Rotary.kt:196)
  at com.google.android.horologist.compose.rotaryinput.DefaultSnapBehavior.snapThreshold(Rotary.kt:597)
  at com.google.android.horologist.compose.rotaryinput.RotaryScrollSnapHandler.handleScrollEvent(Rotary.kt:1020)
  at com.google.android.horologist.compose.rotaryinput.RotaryKt$rotaryHandler$1$1$1$1.invokeSuspend(Rotary.kt:746)
  at com.google.android.horologist.compose.rotaryinput.RotaryKt$rotaryHandler$1$1$1$1.invoke(Unknown Source:8)
  at com.google.android.horologist.compose.rotaryinput.RotaryKt$rotaryHandler$1$1$1$1.invoke(Unknown Source:4)
  at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:214)
  at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Unknown Source:13)
  at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Unknown Source:4)
  at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
  at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:8)
  at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:4)
  at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
  at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
  at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
  at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
  at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
  at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
  at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
  at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:33)
  at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
  at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
  at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
  at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
  at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
  at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:68)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
  at android.view.Choreographer.doCallbacks(Choreographer.java:796)
  at android.view.Choreographer.doFrame(Choreographer.java:727)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
  at android.os.Handler.handleCallback(Handler.java:938)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:223)
  at android.app.ActivityThread.main(ActivityThread.java:7651)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
  Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@ae76536, androidx.compose.runtime.BroadcastFrameClock@320bc37, StandaloneCoroutine{Cancelling}@7d315a4, AndroidUiDispatcher@6505f0d]
```

**Comment by yschimke** [comment]
cc @Kpeved

**Comment by yschimke** [comment]
Do you happen to have empty items?

```
item {
}
```

I think it's a bug either way, just wondering if you have a temporary workaround.

**Comment by garanj** [comment]
I don't have any empty items at the moment... but it's possible I did have before and I've changed the Composable since them (I don't have a history of that file unfortunately).

**Comment by yschimke** [comment]
Low priority
