### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by laiyichin** [google/horologist#1191]
WearDataLayerRegistryTest is failing in CI with the following error

```
com.google.android.horologist.data.WearDataLayerRegistryTest > testPreferencesDataStore[test(AVD) - 11] FAILED 
    kotlinx.coroutines.test.UncompletedCoroutinesError: After waiting for 60000 ms, the test coroutine is not completing
    at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$3$3.invokeSuspend(TestBuilders.kt:342)
```

**Comment by luizgrp** [comment]
also

```
com.google.android.horologist.data.WearLocalDataStoreTest > testConcurrentWrites[test(AVD) - 11] FAILED 
	kotlinx.coroutines.test.UncompletedCoroutinesError: After waiting for 10s, the test coroutine is not completing
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$2$1.invoke(TestBuilders.kt:349)
Tests on test(AVD) - 11 failed: There was 1 failure(s).
```

**Comment by luizgrp** [comment]
```
com.google.android.horologist.networks.NetworkRepositoryTest > testNetworks[test(AVD) - 13] FAILED 
	expected not to be empty
	at com.google.android.horologist.networks.NetworkRepositoryTest$testNetworks$1.invokeSuspend(NetworkRepositoryTest.kt:66)
```

**Comment by luizgrp** [comment]
```
com.google.android.horologist.mediasample.playback.PlaybackErrorTest > testFailingItem[test(AVD) - 13] FAILED 
	kotlinx.coroutines.test.UncompletedCoroutinesError: After waiting for 10s, the test coroutine is not completing, there were active child jobs: [DispatchedCoroutine{Active}@8cf0342]
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$2$1.invoke(TestBuilders.kt:349)
```

**Comment by yschimke** [comment]
Resolved by robolectric?
