### ISSUE TITLE
Media sample is crashing when trying to play

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#1466]
```
2023-07-03 18:02:55.455  2680-2680  AndroidRuntime          com....horologist.mediasample.debug  E  FATAL EXCEPTION: main
            Process: com.google.android.horologist.mediasample.debug, PID: 2680
            java.lang.SecurityException: Neither user 10075 nor current process has android.permission.WAKE_LOCK.
            	at android.os.Parcel.createExceptionOrNull(Parcel.java:2386)
            	at android.os.Parcel.createException(Parcel.java:2370)
            	at android.os.Parcel.readException(Parcel.java:2353)
            	at android.os.Parcel.readException(Parcel.java:2295)
            	at android.os.IPowerManager$Stub$Proxy.acquireWakeLock(IPowerManager.java:916)
            	at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:2463)
            	at android.os.PowerManager$WakeLock.acquire(PowerManager.java:2429)
            	at androidx.media3.exoplayer.WakeLockManager.updateWakeLock(WakeLockManager.java:96)
            	at androidx.media3.exoplayer.WakeLockManager.setStayAwake(WakeLockManager.java:83)
            	at androidx.media3.exoplayer.ExoPlayerImpl.updateWakeAndWifiLock(ExoPlayerImpl.java:2769)
            	at androidx.media3.exoplayer.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:2016)
            	at androidx.media3.exoplayer.ExoPlayerImpl.updatePlayWhenReady(ExoPlayerImpl.java:2752)
            	at androidx.media3.exoplayer.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:810)
            	at androidx.media3.common.BasePlayer.play(BasePlayer.java:114)
            	at com.google.android.horologist.media3.WearConfiguredPlayer$attemptPlay$2$1.invokeSuspend(WearConfiguredPlayer.kt:96)
```

**Comment by luizgrp** [comment]
closing as I realised it was running a potentially old version installed in an old emulator, I don't see the issue with latest from main
