### ISSUE TITLE
DatePickerA11yTest is flaky

### ISSUE THREAD

**Issue by yschimke** [google/horologist#1806]
https://github.com/google/horologist/actions/runs/6844935081/job/18609435240?pr=1805

```
> Task :composables:testDebugUnitTest

com.google.android.horologist.composables.DatePickerA11yTest > interactionTest FAILED
    java.lang.AssertionError at DatePickerA11yTest.kt:65
```

Saw this locally, with a blank screen bitmap.  Possibly a robolectric bug?

**Comment by luizgrp** [comment]
Failed in CI: https://github.com/google/horologist/actions/runs/6945217654/attempts/1?pr=1827

```
java.lang.AssertionError: Snapshot is different from the reference!
Diff stored to: /home/runner/work/horologist/horologist/composables/out/com.google.android.horologist.composables_DatePickerA11yTest_interactionTest_2_delta.png
	at com.google.android.horologist.screenshots.DiffingKt.paparazziCompatibleSnapshot(Diffing.kt:154)
	at com.google.android.horologist.screenshots.DiffingKt.snapshot(Diffing.kt:109)
	at com.google.android.horologist.screenshots.ScreenshotTestRule.saveSnapshot(ScreenshotTestRule.kt:231)
```

![com google android horologist composables_DatePickerA11yTest_interactionTest_2_delta](https://github.com/google/horologist/assets/878134/21800505-b2de-46c7-9703-ddb17ac42556)
