### ISSUE TITLE
Improve API and/or kdoc of installOnNode function

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#1902]
### WHAT

Improve kdoc of `installOnNode` app helper function to suggest developers to handle `RemoteIntentException` or improve API to handle it and return an `AppHelperResultCode`.

### WHY

`RemoteActivityHelper.startRemoteActivity` throws exception if something goes wrong when launching the remote activity:
```
2023-12-20 09:39:40.031 20656-20656 AndroidRuntime          com...logist.datalayer.sample.debug  E  FATAL EXCEPTION: main
    Process: com.google.android.horologist.datalayer.sample.debug, PID: 20656
    androidx.wear.remote.interactions.RemoteActivityHelper$RemoteIntentException: There was an error while starting remote activity.
    	at androidx.wear.remote.interactions.RemoteActivityHelper$RemoteIntentResultReceiver.onReceiveResult(RemoteActivityHelper.kt:317)
    	at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:59)
    	at com.android.internal.os.IResultReceiver$Stub.onTransact(IResultReceiver.java:86)
    	at android.os.Binder.execTransactInternal(Binder.java:1362)
    	at android.os.Binder.execTransact(Binder.java:1301)
    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7dc0883, Dispatchers.Main.immediate]
```

Test scenario: app is not published on Play store.

### HOW

- Assess options and implement it.

**Comment by luizgrp** [comment]
Addressed in https://github.com/google/horologist/pull/1989
