### ISSUE TITLE
Fix VolumeScreenIndividualTest and VolumeScreenThemeTest

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#323]
After merging https://github.com/google/horologist/pull/322, `build` step in main branch got [green](https://github.com/google/horologist/runs/7190095284?check_suite_focus=true).

However, the PRs that are up to date with main branch started to [fail](https://github.com/google/horologist/runs/7192510060?check_suite_focus=true) with:

```
com.google.android.horologist.audio.ui.VolumeScreenIndividualTest > volumeScreenAtMaximum FAILED
    java.lang.NullPointerException at VolumeScreenIndividualTest.kt:66
com.google.android.horologist.audio.ui.VolumeScreenIndividualTest > volumeScreenAtMinimum FAILED
    java.lang.NullPointerException at VolumeScreenIndividualTest.kt:49
com.google.android.horologist.audio.ui.VolumeScreenIndividualTest > volumeScreenWithLongTest FAILED
    java.lang.NullPointerException at VolumeScreenIndividualTest.kt:83
```

---

Once again, main is green, but the PRs that are up to date with main branch started to [fail](https://github.com/google/horologist/runs/7195908369?check_suite_focus=true) with:

```
com.google.android.horologist.audio.ui.VolumeScreenThemeTest > volumeScreenThemes[0] FAILED
    java.lang.NullPointerException at VolumeScreenThemeTest.kt:56
com.google.android.horologist.audio.ui.VolumeScreenThemeTest > volumeScreenThemes[1] FAILED
    java.lang.NullPointerException at VolumeScreenThemeTest.kt:56
com.google.android.horologist.audio.ui.VolumeScreenThemeTest > volumeScreenThemes[2] FAILED
    java.lang.NullPointerException at VolumeScreenThemeTest.kt:56
com.google.android.horologist.audio.ui.VolumeScreenThemeTest > volumeScreenThemes[3] FAILED
    java.lang.NullPointerException at VolumeScreenThemeTest.kt:56
com.google.android.horologist.audio.ui.VolumeScreenThemeTest > volumeScreenThemes[4] FAILED
    java.lang.NullPointerException at VolumeScreenThemeTest.kt:56
com.google.android.horologist.audio.ui.VolumeScreenThemeTest > volumeScreenThemes[5] FAILED
    java.lang.NullPointerException at VolumeScreenThemeTest.kt:56
10 tests completed, 7 failed, 3 skipped
com.google.android.horologist.audio.ui.VolumeScreenThemeTest > volumeScreenThemes[6] FAILED
    java.lang.NullPointerException at VolumeScreenThemeTest.kt:56
```

**Comment by luizgrp** [comment]
Many tests (FigmaVolumeScreenTest, MediaPlayerScreenTest, PodcastPlayerScreenTest, MediaChipTest, ShowPlaylistChipTest, SecondaryChipTest) started [failing](https://github.com/google/horologist/runs/7218704476?check_suite_focus=true) now:

```
com.google.android.horologist.media.ui.FigmaVolumeScreenTest > volumePlayerScreen FAILED
    java.lang.NullPointerException at FigmaVolumeScreenTest.kt:46

...

53 tests completed, 35 failed
> Task :media-ui:testDebugUnitTest FAILED
```


Downloading the build artifacts I can see in the test report:

```
java.lang.NullPointerException: goldenImage must not be null
	at app.cash.paparazzi.SnapshotVerifier$newFrameHandler$1.handle(SnapshotVerifier.kt:53)
	at com.google.android.horologist.paparazzi.WearSnapshotHandler$newFrameHandler$1.handle(WearSnapshotHandler.kt:57)
	at app.cash.paparazzi.Paparazzi$takeSnapshots$1$2.invoke(Paparazzi.kt:302)
	at app.cash.paparazzi.Paparazzi$takeSnapshots$1$2.invoke(Paparazzi.kt:295)
	at app.cash.paparazzi.Paparazzi.withTime(Paparazzi.kt:336)
	at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:295)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:211)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:204)
	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:195)
	at com.google.android.horologist.media.ui.FigmaVolumeScreenTest.volumePlayerScreen(FigmaVolumeScreenTest.kt:46)
```

**Comment by luizgrp** [comment]
Possible scenario for `goldenImage` to be null:

- `SnapshotVerifier.kt:53` calls `ImageIO.read(File)` - [code](https://github.com/cashapp/paparazzi/blob/c420d664509a2b8ed0d92b606a93f1d64c5bd23b/paparazzi/src/main/java/app/cash/paparazzi/SnapshotVerifier.kt#L49)
- `ImageIO.read(File)` calls `ImageIO.read(ImageInputStream)` - [code](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/19fb8f93c59dfd791f62d41f332db9e306bc1422/src/java.desktop/share/classes/javax/imageio/ImageIO.java#L1315)
- `ImageIO.read(ImageInputStream)` calls `ImageIO.getImageReaders` - [code](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/19fb8f93c59dfd791f62d41f332db9e306bc1422/src/java.desktop/share/classes/javax/imageio/ImageIO.java#L1458)
- `ImageIO.getImageReaders` catches `IllegalArgumentException` and returns empty - [code](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/19fb8f93c59dfd791f62d41f332db9e306bc1422/src/java.desktop/share/classes/javax/imageio/ImageIO.java#L656)
- `ImageIO.read(ImageInputStream)` returns null - [code](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/19fb8f93c59dfd791f62d41f332db9e306bc1422/src/java.desktop/share/classes/javax/imageio/ImageIO.java#L1460)
- `ImageIO.read(File)` returns null - [code](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/19fb8f93c59dfd791f62d41f332db9e306bc1422/src/java.desktop/share/classes/javax/imageio/ImageIO.java#L1319)

**Comment by luizgrp** [comment]
After merging https://github.com/google/horologist/pull/337 (red in CI) into main branch (green in CI), main became [red](https://github.com/google/horologist/runs/7231346891?check_suite_focus=true) in CI with the same errors.

So going back to the points listed in https://github.com/google/horologist/issues/323#issuecomment-1175017842:

1) Caching

Cache keys for the commit [before](https://github.com/google/horologist/runs/7218687591?check_suite_focus=true) and [after](https://github.com/google/horologist/runs/7231346891?check_suite_focus=true) are the same, however, the commit before could not find the cache:

```
Cache not found for input keys: gradle-317e5f085fa5f82709737fd17a8c56030dd712840d6d541df61930b48f0ea8f0
```

Whereas the commit after found it:

```
Cache restored from key: gradle-317e5f085fa5f82709737fd17a8c56030dd712840d6d541df61930b48f0ea8f0
```

2) affectedModuleDetector plugin

This https://github.com/google/horologist/pull/337 only changed one file: `build.yml`. Would that make the plugin indicate that all modules have been affected and hence now main is failing (because it is now testing these modules that were not being tested before)?

**Comment by luizgrp** [comment]
Given the causes seems to be unrelated to VolumeScreenIndividualTest and VolumeScreenThemeTest themselves, this is been closed by https://github.com/google/horologist/pull/338 and a new issue was raised in https://github.com/google/horologist/issues/340
