### ISSUE TITLE
 NPE in SnapshotVerifier during tests

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#340]
Most of the tests are failing in CI with:
```
java.lang.NullPointerException: goldenImage must not be null
	at app.cash.paparazzi.SnapshotVerifier$newFrameHandler$1.handle(SnapshotVerifier.kt:53)
	at com.google.android.horologist.paparazzi.WearSnapshotHandler$newFrameHandler$1.handle(WearSnapshotHandler.kt:57)
	at app.cash.paparazzi.Paparazzi$takeSnapshots$1$2.invoke(Paparazzi.kt:302)
	at app.cash.paparazzi.Paparazzi$takeSnapshots$1$2.invoke(Paparazzi.kt:295)
	at app.cash.paparazzi.Paparazzi.withTime(Paparazzi.kt:336)
	at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:295)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:211)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:204)
	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:195)
	at com.google.android.horologist.media.ui.FigmaVolumeScreenTest.volumePlayerScreen(FigmaVolumeScreenTest.kt:46)
```

The stacktrace above can be seen in the test reports in the archived artifact. In the actions logs it displays the following:
```
com.google.android.horologist.media.ui.FigmaVolumeScreenTest > volumePlayerScreen FAILED
    java.lang.NullPointerException at FigmaVolumeScreenTest.kt:46

...

53 tests completed, 35 failed
> Task :media-ui:testDebugUnitTest FAILED
```

Some investigation reported [here](https://github.com/google/horologist/issues/323#issuecomment-1177298063).

Usage of `WearSnapshotHandler` was removed in https://github.com/google/horologist/pull/338 for now.

**Comment by luizgrp** [comment]
Potentially fixed by https://github.com/google/horologist/pull/350; it needs monitoring and this issue can be reopened.
