### ISSUE TITLE
Mark Flaky Tests

### ISSUE THREAD

**Issue by yschimke** [google/horologist#407]
the test runner can skip flaky tests, just running them locally.

**Comment by yschimke** [comment]
```
com.google.android.horologist.media.ui.components.controls.SeekForwardButtonTest > givenIncrementIsOtherValue_thenIconIsDefaultAndDescriptionIsOtherValue[test(AVD) - 11] FAILED 
	java.lang.AssertionError: Activity never becomes requested state "[DESTROYED]" (last lifecycle transition = "RESUMED")
	at androidx.test.core.app.ActivityScenario.waitForActivityToBecomeAnyOf(ActivityScenario.java:338)
```

**Comment by luizgrp** [comment]
https://github.com/google/horologist/runs/7412578257?check_suite_focus=true
```
com.google.android.horologist.media.ui.components.PlayPauseProgressButtonTest > givenIsNOTPlaying_thenPlayButtonIsDisplayed[test(AVD) - 11] FAILED 
	java.lang.AssertionError: Activity never becomes requested state "[DESTROYED]" (last lifecycle transition = "RESUMED")
	at androidx.test.core.app.ActivityScenario.waitForActivityToBecomeAnyOf(ActivityScenario.java:338)
```

https://github.com/google/horologist/runs/7413044501?check_suite_focus=true
```
com.google.android.horologist.media.ui.screens.PlayerScreenTest > givenShowProgressIsFalse_thenProgressBarIsNOTDisplayed[test(AVD) - 11] FAILED 
	java.lang.AssertionError: Activity never becomes requested state "[DESTROYED]" (last lifecycle transition = "RESUMED")
	at androidx.test.core.app.ActivityScenario.waitForActivityToBecomeAnyOf(ActivityScenario.java:338)
```

**Comment by luizgrp** [comment]
Seen it failing bug haven't ignored it yet, listing it here for now:

https://github.com/google/horologist/runs/7501903725?check_suite_focus=true
```
> Task :audio-ui:connectedDebugAndroidTest

com.google.android.horologist.audio.ui.VolumePositionIndicatorTest > testAutoHide[test(AVD) - 11] FAILED 
```

**Comment by yschimke** [comment]
Moving away from instrumentation tests to robolectric
