### ISSUE TITLE
Fix a11y tests

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#535]
Failing in CI with:

[audio-ui](https://github.com/google/horologist/runs/8108379730?check_suite_focus=true):
```
> Task :audio-ui:testDebugUnitTest
292
293com.google.android.horologist.audio.ui.VolumeScreenA11yScreenshotTest > volumeScreenAtMinimums FAILED
294    java.lang.AssertionError at VolumeScreenA11yScreenshotTest.kt:64
```

[media-ui](https://github.com/google/horologist/runs/8111399805?check_suite_focus=true):
```
com.google.android.horologist.media.ui.BrowseScreenA11yScreenshotTest > secondPage FAILED
    java.lang.AssertionError at BrowseScreenA11yScreenshotTest.kt:92

com.google.android.horologist.media.ui.BrowseScreenA11yScreenshotTest > browseScreen FAILED
    java.lang.AssertionError at BrowseScreenA11yScreenshotTest.kt:71

com.google.android.horologist.media.ui.BrowseScreenA11yTallScreenshotTest > browseScreen FAILED
    java.lang.AssertionError at BrowseScreenA11yTallScreenshotTest.kt:69

com.google.android.horologist.media.ui.MediaPlayerA11yScreenshotTest > mediaPlayer FAILED
    java.lang.AssertionError at MediaPlayerA11yScreenshotTest.kt:83


> Task :media-ui:testDebugUnitTest FAILED
104 tests completed, 4 failed
```

**Comment by yschimke** [comment]
```
java.lang.AssertionError: Images differ (by 0.7%) - see details in file:///home/runner/work/horologist/horologist/audio-ui/out/failures/delta-com.google.android.horologist.audio.ui_VolumeScreenA11yScreenshotTest_volumeScreenAtMinimums.png
Thumbnail for current rendering stored at file:///home/runner/work/horologist/horologist/audio-ui/out/failures/com.google.android.horologist.audio.ui_VolumeScreenA11yScreenshotTest_volumeScreenAtMinimums.png
	at org.junit.Assert.fail(Assert.java:89)
	at app.cash.paparazzi.internal.ImageUtils.assertImageSimilar(ImageUtils.kt:207)
	at app.cash.paparazzi.SnapshotVerifier$newFrameHandler$1.handle(SnapshotVerifier.kt:50)
	at com.google.android.horologist.paparazzi.a11y.A11ySnapshotHandler$newFrameHandler$1.handle(A11ySnapshotHandler.kt:71)
	at com.google.android.horologist.paparazzi.WearSnapshotHandler$newFrameHandler$1.handle(WearSnapshotHandler.kt:59)

```

I might bump this, might be JDK differences, and we can probably tolerate 1%,

**Comment by yschimke** [comment]
0.3, 0.5 and 0.9% - bumping to 1%.

**Comment by yschimke** [comment]
Fixed in https://github.com/google/horologist/pull/538
